version: '3.8'

services:

  mysql:
    container_name: zerozero_mysql_db
    image: mysql:8.0.23
    platform: linux/amd64
    ports:
      - '3307:3306'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zerozero
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul

  mongo:
    container_name: zerozero_mongo_db
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    container_name: zerozero_rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    container_name: zerozero_redis
    image: redis:6.0.9
    ports:
      - '6380:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  mongo-data:
  rabbitmq-data:
  redis-data:
