version: '3.8'

services:

  mysql:
    container_name: zerozero_mysql_db
    image: mysql:8.0.23
    platform: linux/amd64
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: zerozero
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      TZ: Asia/Seoul

  mongo:
    container_name: zerozero_mongo_db
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    container_name: zerozero_rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    container_name: zerozero_redis
    image: redis:6.0.9
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mongo-data:
  rabbitmq-data:
