spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zerozero
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 3MB # 파일 하나당 크기
      max-request-size: 15MB # 전송하려는 총 파일 크기

jwt:
  secretKey: ENC(bUGcue0lkiShbjCUGQWvlDs/bBNBWX/dT9LM5CuHg6iyfgiEhgyeT9ZQFEt8vgbpHI7+waQ4GdnkSTqZApygZrfxVvRj1tpTjp5Tqk4sRgvcSXg0SvEChLWPAzxzqylUrkf0pwG4JBdamojvNzENjHijYmXOai3tU4p4Nava3YDecMQOus41f7VRWOFHRBi6HsUvkUg2BqJzovPbLc8dwU5fo0L1mvR+al6IeO4+Xow=)
  expiration: ENC(7B771kWc05bAbt2cQseiBK6cS1mkCho+)
  refresh-token:
    expiration: ENC(TtV+7SDsBOEGp+rbVRoymg6Lx2FYds0B)

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
    id: ENC(+360t44DgPZsqSUxThTfvgjE34sgxwfuKlSkCKVjq10=)
    secret: ENC(Ed98V/o2RX3XhBYyxPMkvyt9jzj2O/xR)

cloud:
  aws:
    credentials:
      accessKey: ENC(uUN+tzVSwP0qiEunRG5TFIv/wcm2EG312EmrcIj5rmc=)
      secretKey: ENC(uPaC8CgR7qRn6K4GH9OpFISRgJaFa85u8b46yUXwPEVFMhBSEb7DUu7azEnZdnM54i9m/aE/raQ=)
    s3:
      bucket: zerozero-cicd-bucket/images
    region:
      static: ap-northeast-2
    stack:
      auto: false