spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ZZCaM677BSas7HxoxUYIchTSuFIBKixZ2YALoTSt+i/ztGfzdXj3q+5JtldPEBHVcs9rrwP36+tVDa/CsbewVgzrWwEyMS4WkY20fVVGZ5BlU+fnFzKCb63AF+d+WgHJ)
    username: ENC(hIB+Lwmf5YEV6Fxhyf83uEKJCwmtwCto)
    password: ENC(mAQQhW6j4EsXca6HtrbdHBsqo+vKqmp5)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB # 파일 하나당 크기
      max-request-size: 15MB # 전송하려는 총 파일 크기

jwt:
  secretKey: ENC(bUGcue0lkiShbjCUGQWvlDs/bBNBWX/dT9LM5CuHg6iyfgiEhgyeT9ZQFEt8vgbpHI7+waQ4GdnkSTqZApygZrfxVvRj1tpTjp5Tqk4sRgvcSXg0SvEChLWPAzxzqylUrkf0pwG4JBdamojvNzENjHijYmXOai3tU4p4Nava3YDecMQOus41f7VRWOFHRBi6HsUvkUg2BqJzovPbLc8dwU5fo0L1mvR+al6IeO4+Xow=)
  expiration: ENC(7B771kWc05bAbt2cQseiBK6cS1mkCho+)
  refresh-token:
    expiration: ENC(TtV+7SDsBOEGp+rbVRoymg6Lx2FYds0B)

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
    id: ENC(+360t44DgPZsqSUxThTfvgjE34sgxwfuKlSkCKVjq10=)
    secret: ENC(Ed98V/o2RX3XhBYyxPMkvyt9jzj2O/xR)

cloud:
  aws:
    credentials:
      accessKey: ENC(YJpgvvWZd5X5K88wZxtcVZZ4OXnps5CvOJj8WjwNFRI=)
      secretKey: ENC(kpo+UFixZRrofHRCa+Ec//dWT6A8ZaaFYQ/bbJJ9GrquNpmOsOaZporG1wAzK1T6RPZPwldrcgI=)
    s3:
      bucket: zerozero-upload/images
    region:
      static: ap-northeast-2
    stack:
      auto: false
