spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
jwt:
  secretKey: ${secretKey}

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
    id: ${X-Naver-Client-Id}
    secret: ${X-Naver-Client-Secret}