spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${Name}
    password: ${Password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jasypt:
  encryptor:
    password: ${JASYPT_SECRETE_KEY}

jwt:
  secretKey: ${secretKey}
#  secretKey: ENC(bUGcue0lkiShbjCUGQWvlDs/bBNBWX/dT9LM5CuHg6iyfgiEhgyeT9ZQFEt8vgbpHI7+waQ4GdnkSTqZApygZrfxVvRj1tpTjp5Tqk4sRgvcSXg0SvEChLWPAzxzqylUrkf0pwG4JBdamojvNzENjHijYmXOai3tU4p4Nava3YDecMQOus41f7VRWOFHRBi6HsUvkUg2BqJzovPbLc8dwU5fo0L1mvR+al6IeO4+Xow=)

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
  client:
#    id: ENC(+360t44DgPZsqSUxThTfvgjE34sgxwfuKlSkCKVjq10=)
    id: ${X-Naver-Client-Id}
#    secret: ENC(Ed98V/o2RX3XhBYyxPMkvyt9jzj2O/xR)
    secret: ${X-Naver-Client-Secret}