package com.zerozero.domain.store.domain;

public enum ZeroDrinks {
  COCA_COLA_ZERO,
  PEPSI_ZERO,
  SPRITE_ZERO,
  CHILSUNG_CIDER_ZERO,
  DR_PEPPER_ZERO,
  MILKIS_ZERO,
  TAMS_ZERO_LEMON,
  TAMS_ZERO_ORANGE,
  TAMS_ZERO_APPLE_KIWI,
  TAMS_ZERO_PINEAPPLE,
  TAMS_ZERO_GRAPE,
  TAMS_ZERO_BLUEBERRY_POMEGRANATE,
  WELCHS_ZERO_GRAPE,
  WELCHS_ZERO_ORANGE,
  WELCHS_ZERO_SHINE_MUSCAT,
  FANTA_ZERO_GRAPE,
  FANTA_ZERO_PINEAPPLE
}
